[SERVICE]
    Flush        1

[INPUT]
    Name         tail
    Path         /var/logs/spring-boot/mood-board-service.log
    Tag          mood-board-service
    Read_from_Head true

[INPUT]
    Name         tail
    Path         /var/logs/spring-boot/geography-service.log
    Tag          geography-service
    Read_from_Head true

[FILTER]
    Name         record_modifier
    Match        mood-board-service
    Record       service mood-board-service

[FILTER]
    Name         record_modifier
    Match        geography-service
    Record       service geography-service

[OUTPUT]
    Name         opensearch
    Match        *
    Host         opensearch
    Port         9200
    Index        microservices-logs
    Type         _doc
    Suppress_Type_Name On
    HTTP_User    admin
    HTTP_Pass    Admin@12345
    tls          On
    tls.verify   Off
