global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'mood-board-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['mood-board-compose:8081']

  - job_name: 'geography-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['geography-compose:8082']
